import { Alert, Button, Card, Input, List, message, QRCode, Select, Space, Typography } from "antd";
import { QrcodeOutlined } from "@ant-design/icons";
import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router";
import { apiClient } from "../../providers/apiClient";
import type { CaseReport, TeacherCase, TeacherLevel } from "../../types/api";
import { addLevel, canPublishCase, moveLevel } from "../../resources/caseOrder";
import { CaseReport as CaseReportView } from "../../components/reports/CaseReport";

export default function CaseEdit({create=false}:{create?:boolean}){
 const{id}=useParams();const navigate=useNavigate();const[levels,setLevels]=useState<TeacherLevel[]>([]);const[item,setItem]=useState<TeacherCase>();const[report,setReport]=useState<CaseReport>();const[title,setTitle]=useState("");const[description,setDescription]=useState("");const[selected,setSelected]=useState<string[]>([]);const[shareUrl,setShareUrl]=useState("");const[error,setError]=useState("");
 useEffect(()=>{apiClient.request("/api/teacher/levels").then(x=>setLevels(x as TeacherLevel[]));if(!create&&id)apiClient.request(`/api/teacher/cases/${id}`).then(x=>{const c=x as TeacherCase;setItem(c);setTitle(c.title);setDescription(c.description);setSelected(c.levels.sort((a,b)=>a.order-b.order).map(l=>l.levelVersionId));});},[create,id]);
 useEffect(()=>{if(id&&!create)apiClient.request(`/api/teacher/cases/${id}/report`).then(x=>setReport(x as CaseReport)).catch(()=>{});},[id,create,item?.isPublished]);
 const versions=useMemo(()=>levels.flatMap(l=>[{value:l.currentVersionId,label:`${l.title} · v${l.version}`}]),[levels]);
 const save=async()=>{setError("");try{const body={caseType:"orderedLevels",title,description,orderedLevelVersionIds:selected};const c=item?await apiClient.request(`/api/teacher/cases/${item.id}`,{method:"PUT",body:JSON.stringify(body)}):await apiClient.request("/api/teacher/cases",{method:"POST",body:JSON.stringify(body)});const saved=c as TeacherCase;setItem(saved);if(create)navigate(`/cases/${saved.id}`,{replace:true});else message.success("Набор сохранён");}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить набор")}};
 const publish=async()=>{if(!item)return;try{setItem(await apiClient.request(`/api/teacher/cases/${item.id}/publish`,{method:"POST"}) as TeacherCase);message.success("Набор опубликован")}catch(e){setError(e instanceof Error?e.message:"Не удалось опубликовать")}};
 const share=async()=>{if(!item)return;try{const result=await apiClient.request(`/api/teacher/cases/${item.id}/share-link`,{method:"POST"}) as {url:string};setShareUrl(new URL(result.url,window.location.origin).href);message.success("QR-ссылка готова. Скопируйте её сейчас.")}catch(e){setError(e instanceof Error?e.message:"Не удалось создать ссылку")}};
 const revoke=async()=>{if(!item)return;await apiClient.request(`/api/teacher/cases/${item.id}/share-link`,{method:"DELETE"});setShareUrl("");setItem({...item,shareLinkActive:false});message.success("QR-ссылка закрыта. История попыток сохранена.")};
 const archive=async()=>{if(!item)return;await apiClient.request(`/api/teacher/cases/${item.id}`,{method:"DELETE"});navigate("/cases")};
 const reorder=(index:number,delta:-1|1)=>setSelected(moveLevel(selected,index,delta));
 return <><Button type="link" href="/admin/cases">← Все наборы</Button><Typography.Title level={2}>{create?"Новый набор":title||"Набор уровней"}</Typography.Title>{error&&<Alert type="error" showIcon message={error} style={{marginBottom:16}}/>}<Card title="Содержание набора"><Space direction="vertical" style={{width:"100%"}} size="middle"><Input size="large" placeholder="Название набора" value={title} onChange={e=>setTitle(e.target.value)}/><Input.TextArea rows={2} placeholder="Описание для учеников" value={description} onChange={e=>setDescription(e.target.value)}/><Select mode="multiple" value={selected} onChange={ids=>setSelected(ids.reduce((all,id)=>addLevel(all,id),[] as string[]))} options={versions} placeholder="Выберите уровни. Повторять уровень нельзя." optionFilterProp="label"/><List bordered dataSource={selected} locale={{emptyText:"Добавьте хотя бы один уровень"}} renderItem={(v,i)=><List.Item actions={[<Button key="up" type="link" disabled={i===0} onClick={()=>reorder(i,-1)}>↑</Button>,<Button key="down" type="link" disabled={i===selected.length-1} onClick={()=>reorder(i,1)}>↓</Button>,<Button key="remove" type="link" danger onClick={()=>setSelected(selected.filter((_,n)=>n!==i))}>Убрать</Button>]}>{i+1}. {versions.find(x=>x.value===v)?.label??v}</List.Item>}/><Space wrap><Button type="primary" onClick={save} disabled={!canPublishCase(title,selected)}>Сохранить набор</Button>{item&&<Button onClick={publish} disabled={!canPublishCase(title,selected)||item.isPublished}>Опубликовать</Button>}{item&&<Button danger onClick={archive}>В архив</Button>}</Space>{item&&<Typography.Text type="secondary">{item.isPublished?"Опубликован":"Черновик"} {item.isPublished&&"· опубликованные версии уровней закреплены"}</Typography.Text>}</Space></Card>
 {item&&<Card title="QR-код" style={{marginTop:20}}><Space direction="vertical">{shareUrl?<><QRCode value={shareUrl} size={210}/><Input readOnly value={shareUrl}/><Button onClick={()=>navigator.clipboard.writeText(shareUrl).then(()=>message.success("Ссылка скопирована"))}>Копировать ссылку</Button><Typography.Text type="secondary">Ссылка показывается один раз. Сохраните её или распечатайте QR-код.</Typography.Text></>:<><Button type="primary" icon={<QrcodeOutlined />} onClick={share} disabled={!item.isPublished}>{item.shareLinkActive?"Перевыпустить QR и показать новую ссылку":"Создать QR"}</Button>{item.shareLinkActive&&<Alert type="warning" message="Активная ссылка была создана раньше и больше не доступна. Перевыпуск отключит предыдущий QR." />}</>}{item.shareLinkActive&&<Button danger onClick={revoke}>Закрыть QR</Button>}</Space></Card>}
 {item&&<Card title="Результаты учеников" style={{marginTop:20}}>{report?<CaseReportView report={report} levelCount={item.levels.length}/>:<Typography.Text type="secondary">Попыток пока нет</Typography.Text>}</Card>}
 </>;
}
